# Generated by Django 3.0.6 on 2020-10-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('database_dump', models.FileField(upload_to='fs_dump', verbose_name='database dump')),
                ('media_dump', models.FileField(upload_to='fs_dump', verbose_name='media dump')),
                ('output', models.TextField(verbose_name='output')),
            ],
            options={
                'verbose_name': 'dump',
                'verbose_name_plural': 'dumps',
            },
        ),
    ]
