# Generated by Django 4.2.16 on 2024-11-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs_dump', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dump',
            name='output',
        ),
        migrations.AlterField(
            model_name='dump',
            name='database_dump',
            field=models.FileField(blank=True, null=True, upload_to='fs_dump', verbose_name='database dump'),
        ),
        migrations.AlterField(
            model_name='dump',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dump',
            name='media_dump',
            field=models.FileField(blank=True, null=True, upload_to='fs_dump', verbose_name='media dump'),
        ),
    ]
